### ISSUE TITLE
Read Tasks/Env config params and Update args Traceback (most recent call last):   File "/home/siyuan/anaconda3/envs/humanoid/meta-qlearning-humanoid/models/run.py", line 392, in <module>     config_tasks_envs(args)   File "/home/siyuan/anaconda3/envs/humanoid/meta-qlearning-humanoid/models/run.py", line 157, in config_tasks_envs     configs = read_json(eparams.env_configs)[eparams.env_name]   File "/home/siyuan/anaconda3/envs/humanoid/meta-qlearning-humanoid/misc/utils.py", line 76, in read_json     file_info = json.load(open(input_json, 'r')) FileNotFoundError: [Errno 2] No such file or directory: './configs/pearl_envs.json'

### ISSUE THREAD

**Issue by SiyuanGao0073** [gokulp01/meta-qlearning-humanoid#2]
I follow the readme instruction but encounter with this issue, and I can not find pear_envs.json in the repo.

**Comment by gokulp01** [comment]
Hello, you are supposed to create a pearl_envs.json. Here is an example: 
```
{"ant-dir": {"n_train_tasks": 2, "n_eval_tasks": 2, "n_tasks": 2, "randomize_tasks": true, "low_gear": false, "forward_backward": true, "num_evals": 4, "num_steps_per_task": 400, "num_steps_per_eval": 400, "num_train_steps_per_itr": 4000}, "ant-goal": {"n_train_tasks": 150, "n_eval_tasks": 30, "n_tasks": 180, "randomize_tasks": true, "low_gear": false, "num_evals": 2, "num_steps_per_task": 1000, "num_steps_per_eval": 400, "num_train_steps_per_itr": 1000}, "cheetah-dir": {"n_train_tasks": 2, "n_eval_tasks": 2, "n_tasks": 2, "randomize_tasks": true, "num_evals": 4, "num_steps_per_task": 1000, "num_steps_per_eval": 400, "num_train_steps_per_itr": 2000}, "cheetah-vel": {"n_train_tasks": 100, "n_eval_tasks": 30, "n_tasks": 130, "randomize_tasks": true, "num_evals": 2, "num_steps_per_eval": 400, "num_steps_per_task": 400, "num_train_steps_per_itr": 2000}, "humanoid-dir": {"n_train_tasks": 100, "n_eval_tasks": 30, "n_tasks": 130, "randomize_tasks": true, "num_evals": 2, "num_steps_per_task": 400, "num_steps_per_eval": 400, "num_train_steps_per_itr": 4000}, "walker-rand-params": {"n_train_tasks": 40, "n_eval_tasks": 10, "n_tasks": 50, "randomize_tasks": true, "num_evals": 2, "num_steps_per_eval": 400, "num_steps_per_task": 400, "num_train_steps_per_itr": 2000}, "hopper-rand-params": {"n_train_tasks": 40, "n_eval_tasks": 10, "n_tasks": 50, "randomize_tasks": true}, "point-robot": {"n_train_tasks": 80, "n_eval_tasks": 20, "n_tasks": 100, "randomize_tasks": true}, "sparse-point-robot": {"n_train_tasks": 80, "n_eval_tasks": 20, "n_tasks": 100, "randomize_tasks": true}}
```
